<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

// Replaced by RAPIRA ->
********************************************************************************/
/*********************************************************************************
 *
* This file was generated by the RAPIRA Translation Suite ----------
*
***********************************************************************likhobory*/

/*********************************************************************************
 * Description: Defines the Russian language pack for the SuiteCRM application.
*********************************************************************************/
// Replaced by RAPIRA <-

$mod_strings = array(
    'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая):',
    'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая):',
    'LBL_ID' => 'ID',
    'LBL_DATE_ENTERED' => 'Дата создания:',
    'LBL_DATE_MODIFIED' => 'Дата изменения:',
    'LBL_MODIFIED' => 'Изменено',
    'LBL_MODIFIED_NAME' => 'Изменено',
    'LBL_CREATED' => 'Создано',
    'LBL_DESCRIPTION' => 'Текст статьи',
    'LBL_ADDITIONAL_INFO' => 'Резолюция',
    'LBL_DELETED' => 'Удалено',
    'LBL_NAME' => 'Статья',
    'LBL_CREATED_USER' => 'Создано',
    'LBL_MODIFIED_USER' => 'Изменено',
    'LBL_LIST_NAME' => 'Имя',
    'LBL_EDIT_BUTTON' => 'Править',
    'LBL_REMOVE' => 'Удалить',
    'LBL_LIST_FORM_TITLE' => 'Статьи базы знаний',
    'LBL_MODULE_NAME' => 'База знаний',
    'LBL_MODULE_TITLE' => 'База знаний',
    'LBL_HOMEPAGE_TITLE' => 'Моя база знаний',
    'LNK_NEW_RECORD' => 'Добавить статью в базу знаний',
    'LNK_LIST' => 'Статьи базы знаний',
    'LBL_SEARCH_FORM_TITLE' => 'Поиск статей базы знаний',
    'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
    'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
    'LBL_NEW_FORM_TITLE' => 'Создать статью базы знаний',
    'LBL_STATUS' => 'Статус',
    'LBL_REVISION' => 'Версия статьи',
    'LBL_AUTHOR_USER_ID' => 'Автор(ID)',
    'LBL_AUTHOR' => 'Автор статьи',
    'LBL_APPROVER_USER_ID' => 'Кем утверждено(ID)',
    'LBL_APPROVER' => 'Кем утверждено',
);

$mod_strings['LBL_AOK_KB_CATEGORIES_TITLE'] = 'Категории базы знаний';