<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

// Replaced by RAPIRA ->
********************************************************************************/
/*********************************************************************************
 *
* This file was generated by the RAPIRA Translation Suite ----------
*
***********************************************************************likhobory*/

/*********************************************************************************
 * Description: Defines the Russian language pack for the SuiteCRM application.
*********************************************************************************/
// Replaced by RAPIRA <-

$mod_strings = array(
    'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
    'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
    'LBL_ID' => 'ID',
    'LBL_DATE_ENTERED' => 'Дата создания',
    'LBL_DATE_MODIFIED' => 'Дата изменения',
    'LBL_MODIFIED' => 'Изменено',
    'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
    'LBL_CREATED' => 'Создано',
    'LBL_DESCRIPTION' => 'Описание',
    'LBL_DELETED' => 'Удалён',
    'LBL_NAME' => 'Отчёт по расписанию',
    'LBL_CREATED_USER' => 'Создано',
    'LBL_MODIFIED_USER' => 'Изменено',
    'LBL_LIST_NAME' => 'Название',
    'LBL_EDIT_BUTTON' => 'Править',
    'LBL_REMOVE' => 'Удалить',
    'LBL_ANY_EMAIL' => 'Любой E-mail:',
    'LBL_EMAIL_NON_PRIMARY' => 'Доп. E-mail',
    'LBL_ASSIGNED_TO' => 'Ответственный(ая):',
    'LBL_ASSIGNED_USER' => 'Ответственный(ая):',
    'LBL_EMAIL_RECIPIENTS' => 'Получатели:',
    'NTC_DELETE_CONFIRMATION' => 'Вы действительно хотите удалить эту запись?',
    'NTC_SNOOZE_CONFIRMATION' => 'Вы действительно хотите отложить уведомление?',
    'LBL_LIST_FORM_TITLE' => 'Отчёты по расписанию',
    'LBL_MODULE_NAME' => 'Отчёты по расписанию',
    'LBL_MODULE_TITLE' => 'Отчёты по расписанию',
    'LBL_HOMEPAGE_TITLE' => 'Мои отчёты по расписанию',
    'LNK_NEW_RECORD' => 'Создать отчёт по расписанию',
    'LNK_LIST' => 'Отчёты по расписанию',
    'LBL_SEARCH_FORM_TITLE' => 'Поиск отчётов по расписанию',
    'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
    'LBL_NEW_FORM_TITLE' => 'Создать отчёт по расписанию',
    'LBL_SCHEDULE' => 'Расписание',
    'LBL_AOR_REPORT_NAME' => 'Отчёт',
    'LBL_SCHEDULED_REPORTS_INFORMATION' => 'Отчёты по расписанию',
    'LBL_LAST_RUN' => 'Последний запуск',
    'LBL_STATUS' => 'Статус',
);